import {initial,canonical,applyGate,fromAngles,bloch,angles,probabilities,measure} from './quantum.js';
import {formatComplex,formatStateEquation} from './format.js';
import {defaultView,projectBloch} from './projection.js';
let state=initial(),{yaw,pitch}=defaultView,drag=null;
const $=id=>document.getElementById(id);
const descriptions={X:'X swaps |0⟩ and |1⟩: a half-turn about the X axis.',Y:'Y makes a half-turn about the Y axis, including relative-phase changes.',Z:'Z changes the sign of the |1⟩ amplitude: a half-turn about Z.',H:'H maps |0⟩ to (|0⟩ + |1⟩)/√2 and exchanges the X and Z axes.',S:'S adds a relative phase of π/2 to |1⟩: a quarter-turn about Z.',T:'T adds a relative phase of π/4 to |1⟩: an eighth-turn about Z.'};
for(const gate of Object.keys(descriptions)){const button=document.createElement('button');button.textContent=gate;button.setAttribute('aria-label',`Apply ${gate} gate`);button.addEventListener('click',()=>{state=canonical(applyGate(state,gate));$('gateInfo').textContent=descriptions[gate];$('measurementResult').textContent='Apply more gates or measure this state.';update();});$('gates').appendChild(button)}
$('reset').addEventListener('click',()=>{state=initial();$('gateInfo').textContent='Reset to the north pole |0⟩.';$('measurementResult').textContent='Measurement results appear here. Measuring collapses the state.';update()});
for(const id of ['theta','phi']){$(id).addEventListener('input',()=>{state=fromAngles(Number($('theta').value)*Math.PI/180,Number($('phi').value)*Math.PI/180);$('gateInfo').textContent='The angles directly prepare a new pure qubit state.';$('measurementResult').textContent='Apply more gates or measure this state.';update(false)})}
$('measure').addEventListener('click',()=>{const {outcome:result,state:collapsed}=measure(state);state=collapsed;$('measurementResult').textContent=`Outcome |${result}⟩. The state collapsed to |${result}⟩.`;$('gateInfo').textContent='Computational-basis measurement projects the state to the observed basis state.';update()});
function update(syncSliders=true){const [a,b]=canonical(state),[p0,p1]=probabilities(state),an=angles(state);$('alpha').textContent=formatComplex(a);$('beta').textContent=formatComplex(b);$('stateEquation').textContent=formatStateEquation(a,b);$('p0').textContent=`${(p0*100).toFixed(1)}%`;$('p1').textContent=`${(p1*100).toFixed(1)}%`;$('bar0').style.width=`${p0*100}%`;$('bar1').style.width=`${p1*100}%`;const t=Math.round(an.theta*180/Math.PI),p=(Math.abs(Math.sin(an.theta))<1e-9?0:Math.round(an.phi*180/Math.PI))%360;$('angles').textContent=`θ = ${t}° · φ = ${p}°`;if(syncSliders){$('theta').value=t;$('phi').value=p;}$('thetaVal').textContent=`${$('theta').value}°`;$('phiVal').textContent=`${$('phi').value}°`;draw()}
const canvas=$('sphere'),ctx=canvas.getContext('2d');
function draw(){const W=canvas.width,H=canvas.height,cx=W/2,cy=H/2,r=Math.min(W,H)*.365;ctx.clearRect(0,0,W,H);const project=v=>{const p=projectBloch(v,yaw,pitch);return {x:cx+r*p.right,y:cy-r*p.up,depth:p.depth}};
const origin=project({x:0,y:0,z:0});function line(a,b,color,width=1.4,dash=[]){const A=project(a),B=project(b);ctx.beginPath();ctx.setLineDash(dash);ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.setLineDash([])}
const glow=ctx.createRadialGradient(cx-r*.3,cy-r*.4,r*.05,cx,cy,r);glow.addColorStop(0,'rgba(76,129,245,.21)');glow.addColorStop(1,'rgba(76,129,245,.045)');ctx.beginPath();ctx.arc(cx,cy,r,0,2*Math.PI);ctx.fillStyle=glow;ctx.fill();ctx.strokeStyle='#5174ab';ctx.lineWidth=2;ctx.stroke();
// Arcs on the far hemisphere are dashed and dimmed so the viewer can tell front from back (and hence handedness).
function circle(plane,color){const points=[];for(let i=0;i<=180;i++){const t=i*2*Math.PI/180;points.push(project(plane(t)))}ctx.strokeStyle=color;ctx.lineWidth=1.35;for(const back of [true,false]){ctx.setLineDash(back?[4,5]:[]);ctx.globalAlpha=back?.45:1;ctx.beginPath();for(let i=1;i<points.length;i++){if((points[i-1].depth+points[i].depth<0)!==back)continue;ctx.moveTo(points[i-1].x,points[i-1].y);ctx.lineTo(points[i].x,points[i].y)}ctx.stroke()}ctx.setLineDash([]);ctx.globalAlpha=1}
circle(t=>({x:Math.cos(t),y:Math.sin(t),z:0}),'#4971a6');circle(t=>({x:Math.cos(t),y:0,z:Math.sin(t)}),'#355980');circle(t=>({x:0,y:Math.cos(t),z:Math.sin(t)}),'#355980');
for(const axis of [{v:{x:1.2,y:0,z:0},label:'+X'},{v:{x:0,y:1.2,z:0},label:'+Y'},{v:{x:0,y:0,z:1.2},label:'|0⟩'},{v:{x:0,y:0,z:-1.2},label:'|1⟩'}]){line({x:0,y:0,z:0},axis.v,'#8099c0',1.5,[4,5]);const a=project(axis.v);ctx.fillStyle='#dbeaff';ctx.font='bold 18px system-ui';ctx.fillText(axis.label,a.x+5,a.y-5)}
const vector=bloch(state);line({x:0,y:0,z:0},vector,'#ffcf69',5);const end=project(vector);ctx.beginPath();ctx.arc(end.x,end.y,8,0,2*Math.PI);ctx.fillStyle='#ffcf69';ctx.globalAlpha=end.depth<-1e-9?.55:1;ctx.fill();ctx.globalAlpha=1;ctx.beginPath();ctx.arc(origin.x,origin.y,3,0,2*Math.PI);ctx.fillStyle='#cad9ff';ctx.fill()}
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw=drag.yaw+(e.clientX-drag.x)*.008;pitch=Math.max(-1.4,Math.min(1.4,drag.pitch+(e.clientY-drag.y)*.006));draw()});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);update();
